<?php

return [
    [
        "module" => "spamprotection",
        "upstream" => "silverstripe/silverstripe-spamprotection",
        "origin" => "helpfulrobot/silverstripe-spamprotection",
        "folder" => "silverstripe-spamprotection",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "contentreview",
        "upstream" => "silverstripe/silverstripe-contentreview",
        "origin" => "helpfulrobot/silverstripe-contentreview",
        "folder" => "silverstripe-contentreview",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "multiform",
        "upstream" => "silverstripe/silverstripe-multiform",
        "origin" => "helpfulrobot/silverstripe-multiform",
        "folder" => "silverstripe-multiform",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "userforms",
        "upstream" => "silverstripe/silverstripe-userforms",
        "origin" => "helpfulrobot/silverstripe-userforms",
        "folder" => "silverstripe-userforms",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "advancedworkflow",
        "upstream" => "silverstripe-australia/advancedworkflow",
        "origin" => "helpfulrobot/advancedworkflow",
        "folder" => "advancedworkflow",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Australia",
    ],
    [
        "module" => "akismet",
        "upstream" => "silverstripe/silverstripe-akismet",
        "origin" => "helpfulrobot/silverstripe-akismet",
        "folder" => "silverstripe-akismet",
        "license" => "BSD-3-Clause",
        "owner" => "Damian Mooyman",
    ],
    [
        "module" => "blog",
        "upstream" => "silverstripe/silverstripe-blog",
        "origin" => "helpfulrobot/silverstripe-blog",
        "folder" => "silverstripe-blog",
        "license" => "BSD-2-Clause",
        "owner" => "Michael Strong",
    ],
    [
        "module" => "comment-notifications",
        "upstream" => "silverstripe-labs/comment-notifications",
        "origin" => "helpfulrobot/comment-notifications",
        "folder" => "comment-notifications",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "comments",
        "upstream" => "silverstripe/silverstripe-comments",
        "origin" => "helpfulrobot/silverstripe-comments",
        "folder" => "silverstripe-comments",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "content-widget",
        "upstream" => "silverstripe-labs/silverstripe-content-widget",
        "origin" => "helpfulrobot/silverstripe-content-widget",
        "folder" => "silverstripe-content-widget",
        "license" => "MIT",
        "owner" => "Jeremy Shipman",
    ],
    [
        "module" => "environmentcheck",
        "upstream" => "silverstripe-labs/silverstripe-environmentcheck",
        "origin" => "helpfulrobot/silverstripe-environmentcheck",
        "folder" => "silverstripe-environmentcheck",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "externallinks",
        "upstream" => "silverstripe-labs/silverstripe-externallinks",
        "origin" => "helpfulrobot/silverstripe-externallinks",
        "folder" => "silverstripe-externallinks",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "fulltextsearch",
        "upstream" => "silverstripe-labs/silverstripe-fulltextsearch",
        "origin" => "helpfulrobot/silverstripe-fulltextsearch",
        "folder" => "silverstripe-fulltextsearch",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "html5",
        "upstream" => "silverstripe/silverstripe-html5",
        "origin" => "helpfulrobot/silverstripe-html5",
        "folder" => "silverstripe-html5",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "hybridsessions",
        "upstream" => "silverstripe-labs/silverstripe-hybridsessions",
        "origin" => "helpfulrobot/silverstripe-hybridsessions",
        "folder" => "silverstripe-hybridsessions",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "iframe",
        "upstream" => "silverstripe-labs/silverstripe-iframe",
        "origin" => "helpfulrobot/silverstripe-iframe",
        "folder" => "silverstripe-iframe",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "lumberjack",
        "upstream" => "silverstripe/silverstripe-lumberjack",
        "origin" => "helpfulrobot/silverstripe-lumberjack",
        "folder" => "silverstripe-lumberjack",
        "license" => "BSD-2-Clause",
        "owner" => "Michael Strong",
    ],
    [
        "module" => "mimevalidator",
        "upstream" => "silverstripe-labs/silverstripe-mimevalidator",
        "origin" => "helpfulrobot/silverstripe-mimevalidator",
        "folder" => "silverstripe-mimevalidator",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "multivaluefield",
        "upstream" => "silverstripe-australia/silverstripe-multivaluefield",
        "origin" => "helpfulrobot/silverstripe-multivaluefield",
        "folder" => "silverstripe-multivaluefield",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Australia",
    ],
    [
        "module" => "queuedjobs",
        "upstream" => "silverstripe-australia/silverstripe-queuedjobs",
        "origin" => "helpfulrobot/silverstripe-queuedjobs",
        "folder" => "silverstripe-queuedjobs",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Australia",
    ],
    [
        "module" => "registry",
        "upstream" => "silverstripe-labs/silverstripe-registry",
        "origin" => "helpfulrobot/silverstripe-registry",
        "folder" => "silverstripe-registry",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "restfulserver",
        "upstream" => "silverstripe/silverstripe-restfulserver",
        "origin" => "helpfulrobot/silverstripe-restfulserver",
        "folder" => "silverstripe-restfulserver",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "secureassets",
        "upstream" => "silverstripe-labs/silverstripe-secureassets",
        "origin" => "helpfulrobot/silverstripe-secureassets",
        "folder" => "silverstripe-secureassets",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "securityreport",
        "upstream" => "silverstripe-labs/silverstripe-securityreport",
        "origin" => "helpfulrobot/silverstripe-securityreport",
        "folder" => "silverstripe-securityreport",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "selectupload",
        "upstream" => "silverstripe-labs/silverstripe-selectupload",
        "origin" => "helpfulrobot/silverstripe-selectupload",
        "folder" => "silverstripe-selectupload",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "spellcheck",
        "upstream" => "silverstripe-labs/silverstripe-spellcheck",
        "origin" => "helpfulrobot/silverstripe-spellcheck",
        "folder" => "silverstripe-spellcheck",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "subsites",
        "upstream" => "silverstripe/silverstripe-subsites",
        "origin" => "helpfulrobot/silverstripe-subsites",
        "folder" => "silverstripe-subsites",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "tagfield",
        "upstream" => "silverstripe-labs/silverstripe-tagfield",
        "origin" => "helpfulrobot/silverstripe-tagfield",
        "folder" => "silverstripe-tagfield",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "taxonomy",
        "upstream" => "silverstripe-labs/silverstripe-taxonomy",
        "origin" => "helpfulrobot/silverstripe-taxonomy",
        "folder" => "silverstripe-taxonomy",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "textextraction",
        "upstream" => "silverstripe-labs/silverstripe-textextraction",
        "origin" => "helpfulrobot/silverstripe-textextraction",
        "folder" => "silverstripe-textextraction",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "translatable",
        "upstream" => "silverstripe/silverstripe-translatable",
        "origin" => "helpfulrobot/silverstripe-translatable",
        "folder" => "silverstripe-translatable",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "versionedfiles",
        "upstream" => "silverstripe-australia/silverstripe-versionedfiles",
        "origin" => "helpfulrobot/silverstripe-versionedfiles",
        "folder" => "silverstripe-versionedfiles",
        "license" => "BSD-3-Clause",
        "owner" => "Andrew Short",
    ],
    [
        "module" => "versionfeed",
        "upstream" => "silverstripe-labs/silverstripe-versionfeed",
        "origin" => "helpfulrobot/silverstripe-versionfeed",
        "folder" => "silverstripe-versionfeed",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "widgets",
        "upstream" => "silverstripe/silverstripe-widgets",
        "origin" => "helpfulrobot/silverstripe-widgets",
        "folder" => "silverstripe-widgets",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "fluent",
        "upstream" => "tractorcow/silverstripe-fluent",
        "origin" => "helpfulrobot/silverstripe-fluent",
        "folder" => "silverstripe-fluent",
        "license" => "BSD-3-Clause",
        "owner" => "Damian Mooyman",
    ],
    [
        "module" => "module",
        "upstream" => "silverstripe/silverstripe-module",
        "origin" => "helpfulrobot/silverstripe-module",
        "folder" => "silverstripe-module",
        "license" => "BSD-3-Clause",
        "owner" => "Cam Findlay",
    ],
    [
        "module" => "fluent-regional",
        "upstream" => "silverstripe/fluent-regional",
        "origin" => "helpfulrobot/fluent-regional",
        "folder" => "fluent-regional",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "docsviewer",
        "upstream" => "silverstripe/silverstripe-docsviewer",
        "origin" => "helpfulrobot/silverstripe-docsviewer",
        "folder" => "silverstripe-docsviewer",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "siteconfig",
        "upstream" => "silverstripe/silverstripe-siteconfig",
        "origin" => "helpfulrobot/silverstripe-siteconfig",
        "folder" => "silverstripe-siteconfig",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "sitewidecontent-report",
        "upstream" => "silverstripe/silverstripe-sitewidecontent-report",
        "origin" => "helpfulrobot/silverstripe-sitewidecontent-report",
        "folder" => "silverstripe-sitewidecontent-report",
        "license" => "BSD-3-Clause",
        "owner" => "Carlos Barberis",
    ],
    [
        "module" => "activedirectory",
        "upstream" => "silverstripe/silverstripe-activedirectory",
        "origin" => "helpfulrobot/silverstripe-activedirectory",
        "folder" => "silverstripe-activedirectory",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "forum",
        "upstream" => "silverstripe/silverstripe-forum",
        "origin" => "helpfulrobot/silverstripe-forum",
        "folder" => "silverstripe-forum",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "mathspamprotection",
        "upstream" => "silverstripe/silverstripe-mathspamprotection",
        "origin" => "helpfulrobot/silverstripe-mathspamprotection",
        "folder" => "silverstripe-mathspamprotection",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "multi-domain",
        "upstream" => "silverstripe/multi-domain",
        "origin" => "helpfulrobot/multi-domain",
        "folder" => "multi-domain",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "globaltoolbar",
        "upstream" => "silverstripe/silverstripe-globaltoolbar",
        "origin" => "helpfulrobot/silverstripe-globaltoolbar",
        "folder" => "silverstripe-globaltoolbar",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "mollom",
        "upstream" => "silverstripe/silverstripe-mollom",
        "origin" => "helpfulrobot/silverstripe-mollom",
        "folder" => "silverstripe-mollom",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "mobile",
        "upstream" => "silverstripe/silverstripe-mobile",
        "origin" => "helpfulrobot/silverstripe-mobile",
        "folder" => "silverstripe-mobile",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "content-notifier",
        "upstream" => "silverstripe/silverstripe-content-notifier",
        "origin" => "helpfulrobot/silverstripe-content-notifier",
        "folder" => "silverstripe-content-notifier",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
    [
        "module" => "dynamodb",
        "upstream" => "silverstripe/silverstripe-dynamodb",
        "origin" => "helpfulrobot/silverstripe-dynamodb",
        "folder" => "silverstripe-dynamodb",
        "license" => "BSD-3-Clause",
        "owner" => "SilverStripe Limited",
    ],
];
